### ISSUE TITLE
Atualização de um subitem em uma assinatura

### ISSUE THREAD

**Issue by HenriqueMunhoz** [iugu/iugu-ruby#31]
Buenas,

Estou tentando atualizar um subitem de uma assinatura ou ate mesmo deletado porem quando faço a requisição ele me diz que preciso mandar 1 argumento junto.

subs = Iugu:Subscription.fetch(id: ID_DA_ASSINATURA)
subs.subitems = [{ "description": "Item um", "quantity": 1, "price_cents": 1000, "price": "R$ 1000000,00", "total": "R$ 10,00" }]
subs.save

Ok, até aqui funciona e ele salva certinho, porem eu nao consigo mais atualizar esse item e nem mesmo deleta-lo, alguém tem alguma ideia?

Dês de já, agradeço!

**Comment by HenriqueMunhoz** [comment]
Quando eu faço o seguinte comando

subs.subitems.delete

Ele me retorna que o "method delete needs 1 more argument"

**Comment by WilliamCSA04** [comment]
Estou tendo este mesmo problema atualmente. Não consigo atualizar um subitem pela gem.

Até tentei dar fork no projeto e criei o seguinte método:
`

     def change_subitems(subitems, options = {})
      options.merge!({ subitems: subitems })
      Iugu::Factory.create_from_response(self.class.object_type,
                                          APIRequest.request("PUT",
                                                            "#{self.class.url(self.id)}/",
                                                            options))
     end
`

E tento passar o seguinte objeto: `{id: "user_limit_exceeded:destroy_false", description: "test", price_cents: 50000, quantity: 1, recurrent: true}` como parâmetro do subitem.

E o retorno que me da é:  400 Bad Request
